apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type:  NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    nodePort:  30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name:  nginx-2
      labels:
        app:  myapp
    spec:
      containers:
      - name: nginx
        image: nginx